name: ğŸ§Š GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "30 5 * * *"
  push:
    branches:
      - main
  workflow_dispatch: {}  # â† Perbaikan disini

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate GitHub Contributions (night blue)
    permissions:
      contents: write

    steps:
      - name: ğŸ”„ Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ğŸ¨ Generate GitHub Profile 3D (Night blue)
        uses: yoshi389111/github-profile-3d-contrib@0.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: zreechxnn
        with:
          args: --theme "night-blue"

      - name: ğŸ“ Pindahkan hasil ke folder dist/
        run: |
          mkdir -p dist
          cp -r out/* dist/

      - name: ğŸš€ Push hasil ke branch `output`
        uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
